service: x-services
frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-middleware
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

custom:
  middleware:
    pre:
      - middleware-functions/handler.validator
    pos:
      - middleware-functions/handler.timer

functions:
  login:
    handler: auth-functions/handler.login
    events:
      - httpApi:
          path: /login
          method: post
    environment:
      AUTH_SECRET_KEY: ${env:AUTH_SECRET_KEY}
    cors: true

  sign-up:
    handler:
      - auth-functions/handler.verifyToken
      - auth-functions/handler.signUp
    events:
      - httpApi:
          path: /sign-up
          method: post
