service: x-services
frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-middleware
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ${env:AWS_REGION}

functions:
  login:
    handler: auth-functions/handler.login
    events:
      - httpApi:
          path: /login
          method: get
    environment:
      AUTH_SECRET_KEY: ${env:AUTH_SECRET_KEY}
